# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 527802ef0ddb990e268e235a9a193dbf3644b34b30481e9718669a2a2d76b2784199cca6e05cf421d80e4658895c8bb6f1d6dbbaf6b86f19c71ed80acccc8c18

test:
  secret_key_base: 4eda2069790ba999602dcb1971cda944cb482f3e2da9fafa4db99cf97c1b4a27c9de5f76d239fd96e235ea234075ad8a83ebd445e06056f21bca2d8440caa49d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
